### ISSUE TITLE
Slow Performance Using MERGE

### ISSUE THREAD

**Issue by zzxx-husky** [RedisGraph/RedisGraph#1067]
Hi,

I am new to RedisGraph but I am quite interested in it. Right now I am playing with RedisGraph for some simple scenarios. I load 100K edges (with ~887~ 1059887 vertices) into RedisGraph using ~[bulk_insert](https://github.com/RedisGraph/RedisGraph/tree/master/demo/bulk_insert)~ [bulk_loader](https://github.com/redisgraph/redisgraph-bulk-loader) and it takes 20+ seconds. Based on that, I tried to add some edge updates to the base graph. I find that I have to use MERGE in the query as I don't want to create duplicate vertices. But then it takes around 2900+ seconds to merge 1000 edges (these 1000 edge udpates are sent to RedisGraph using a single Cypher query). Do you have any suggestion to improve the performance for loading edge updates?

Thanks in advance!

**Comment by jeffreylovitz** [comment]
Hi @zzxx-husky,

The bulk insert tool is designed expressly to be fast, and doesn't need to do a lot of the work that a full Cypher query would, so ultimately the latter is likely to fall somewhat short by that metric.

That said, the MERGE times you're describing are not what I would expect! Are you free to share a sample MERGE query, or better, full steps to reproduce?

As an aside, the bulk insert tool hosted at https://github.com/redisgraph/redisgraph-bulk-loader is a bit more up-to-date than the demo one provided. I believe most of the differences currently regard data type interpolation and relatively minor things, but would recommend using it regardless!

**Comment by zzxx-husky** [comment]
Hi @jeffreylovitz ,

Thanks for your reply.

> As an aside, the bulk insert tool hosted at https://github.com/redisgraph/redisgraph-bulk-loader is a bit more up-to-date than the demo one provided. I believe most of the differences currently regard data type interpolation and relatively minor things, but would recommend using it regardless!

:sweat_smile: I double checked and found that I was actually using the bulk-loader you are referring to. Sorry for the mistake.

> Are you free to share a sample MERGE query, or better, full steps to reproduce?

Yes, we create a [repo](https://github.com/zzxx-husky/RedisGraphTrials) and upload the base graph data (100K edges with 1059887 vertices) and the cypher query we used to add 1K edge updates. Would you please take a look?

**Comment by jeffreylovitz** [comment]
Hey @zzxx-husky ,

That is a very intense query!

The first issue is pretty straightforward, which is that the bulk loader infers that your `name` properties are integers, but your MERGE queries place them in quotes, and `"3070959" <> 3070959`. As such, I'd expect 0 successful matches in MERGE, and every entity will be newly created. For the rest of this answer, I'll remove erroneous quotes.

You're following good practices regarding the independence of elements in MERGE clauses, since: 
```
MERGE (n3070959:n1{name:3070959})
MERGE (n72780846:n0{name:72780846})
MERGE (n3070959)-[:e18{batch:1}]->(n72780846)
```
will not create duplicate vertices if an endpoint is not resolved, while the more naive query:
```
MERGE (n3070959:n1{name:3070959})-[:e18{batch:1}]->(n72780846:n0{name:72780846})
```
Will create duplicate nodes whenever one endpoint doesn't exist.

The consequence of MERGE independence, though, is that we can't collapse multiple MERGE ops into a single one - each has the potential to depend on the output of a previous one. Even your 10-edge example will build an operation tree of 130 ops!

There's not really a one-size-fits-all fix for this case, it will generally depend on what guarantees you have about your data and whether the atomicity of a single query is a must-have.

Some general advice is to use indexes when you're repeatedly looking nodes with a specific property, which in your case we'll accomplish with:
```
GRAPH.QUERY pm_test CREATE INDEX ON :n0(name)
GRAPH.QUERY pm_test CREATE INDEX ON :n1(name)
```
This allows us to fold the Label Scan and Filter ops into a single optimized Index Scan, which should benefit performance.

Next we should ask why some endpoints are not being resolved - did we expect the bulk loader to create all the nodes we need, or is the edge update logic supposed to introduce new nodes as well? If the former is the case, re-check your inputs. If you can make that guarantee, you can use either the naive MERGE format above or logic like:
```
MATCH (n3070959:n1{name:3070959}), (n72780846:n0{name:72780846})
MERGE (n3070959)-[:e18{batch:1}]->(n72780846)
```

If there are rules governing how edges are being introduced, those should also be exploited in the query. For example, `n72780846` is having ~100 incoming edges introduced. If the nodes they're being connected to have some identifying feature, we can have a single MERGE op processing multiple inputs instead of each processing just one. To use a contrived example, let's pretend all sources have a name < 1000000, in which case we can write:
```
MATCH (n72780846:n0{name:72780846}), (src:n1) WHERE src.name < 1000000
MERGE (src)-[:e18{batch:1}]->(n72780846)
```
This creates and sets the batch property on 113,986 new edges in 2.8 seconds.

As a final note, I'm worried about stack overflows with queries that introduce this many ops in general. If you can write more queries with lower complexity, you will be a lot safer.

Hope this helped!

**Comment by DvirDukhan** [comment]
@zzxx-husky 
try parameterized queries instead of one big multiple merge query
I assume tou can read your data files into a stream or array of tuples (for example)
so this is possible solution
```
redis_graph = Graph('your graph', redis_con)
data = ["Your (src, dest,butch) tuples from file"]
for (src_name, dest_name, batch) in data:
    parmas = {"src_name": src_name, "dest_name": dest_name, "batch": batch}
     redis_graph.query("MERGE (src:n1{name:$src_name}) MERGE (dest:n0{name:$dest_name}) MERGE (src)-[:e18{batch:$batch}]->(dest)")
```

**Comment by zzxx-husky** [comment]
Hi @jeffreylovitz ,

Thank you for your detailed and helpful advices! We tried and met some new problems about the memory usage and we spent quite some time on the problems. (That's the reason for the late response :( ... )

Following your advices, we managed to find out all the verteices (that could appear when we insert edge updates later) and tried to insert all of them using bulk loader. We want to load all the verteices into RedisGraph by bulk loader, such that we can build index (as you suggested) on the vertices to speed up the succeeding processing.

Here is the problem. As we tested, with the number of vertices being around 107M, if we only load all the vertices without loading any edge, RedisGraph uses around 20G memory; if we load both vertices and edges, it uses around 115G while our machine memory is 128G. The memory usage is too high to be believable. We tried to disable the persistence of Redis but that does not help reduce the memory usage. Do you have any suggestion on the problem?


Hi @DvirDukhan ,

You suggestion to split the big query into multiple smaller ones looks helpful. I think the problem of a big query is that it creates too many operations, which is much more than the total number of operations that small queries would create? I will tried that later on! Thanks!

**Comment by jeffreylovitz** [comment]
Is 115G the peak memory consumption during the bulk loader process, or the memory consumption of the server once bulk loading has finished?

**Comment by zzxx-husky** [comment]
The 115G is the memory consumption when the bulk loading finishes.

**Comment by jeffreylovitz** [comment]
Wow! I agree with your assessment of "too high to be believable".

Are you using the same sample data as before?

I just tested loading that locally with [this script](https://gist.github.com/jeffreylovitz/1b46014befb505d57c0cc6862172ae0c).

The ultimate output was:
`Construction of graph 'G' complete: 1059887 nodes created, 100000 relations created in 12.689978 seconds`

The memory overhead afterwards is 540M in RAM and about 1G in virtual memory, which seems plausible to me.

Has your data changed a lot?

**Comment by zzxx-husky** [comment]
Yes, the data we use is changed a lot, because we need to include all the vertices that might appear when we insert edge updates. I just uploaded the new dataset we used [here](https://github.com/zzxx-husky/RedisGraphTrials/tree/data2/data2) in a new branch `data2` in case you're interested. (Would you please take a look if possible?)

When we loaded this dataset into RedisGraph, the final output is 
```
Construction of graph 'G' complete: 107603613 nodes created, 10000 relations created in 1785.536259 seconds.
```
The time used and the memory consumption are both high.

**Comment by jeffreylovitz** [comment]
Your new approach creates over 100 million `n0` nodes, which actually makes this graph quite memory-intensive!

Each node label and edge type is associated with a matrix that has the dimensions `node_count * node_count`, since this lets us to perform traversals by directly multiplying matrices without performing a lot of preparatory transformations.

The matrices use a sparse representation, CSR, that makes most of the memory overhead dependent on the number of real values within the matrix. Each matrix's size in bytes is roughly:
`16 * (# of total nodes) + (# of nodes with this label)`.

With 100 million nodes, all of your matrices have an automatic cost of ~1.6 gigs, and you have 48 matrices for your node and edge types. We could definitely get to 115G by factoring in the actual data and other costs.

I would recommend coming up with an approach that only creates nodes that do exist rather than making all nodes that might need to exist.

**Comment by zzxx-husky** [comment]
Hi ~ Just for a wrap-up of this issue, at then end, we use bulk_loader to load a base graph and build index on the vertices. After that, we insert some edge updates into the graph. When loading the base graph, we push all the vertices in the base graph and all the vertices that might appear in the edge updates. Then we can use *MERGE* to find vertices when we push edge updates.

Here are some performance results for loading the base graph and edge updates right now (maybe it is possible to be better?):
+ Loading a base graph with 100K edges takes 4.27s with a final memory usage to be 756MB, and it takes roughly 0.45s to push 1000 new edges every time with index (and 160s without index).
+ Loading a base graph with 1M edges takes 40s with a final (or peak) memory usage to be 1.5G (or 23G), and it takes roughly 0.5s to push 1000 new edges every time with index (and 1200s without index)

As the time for loading edge update is less than 0.5s (due to index), so we do not consider to split a *large* cypher query to *smaller* queries (where each small query insert only one edge update). But appreciate and thanks for the advices !!

I think my problem has been solved, so now maybe let me close this issue. Thanks again for the advices !!
