### ISSUE TITLE
Support full text index/search in a list type property

### ISSUE THREAD

**Issue by renlei-bj** [RedisGraph/RedisGraph#1109]
If the property is a list e.g. ['a','b','c'], the current full text index seems not working at all.

I did some test for this. In my test, I created the full text index on two properties. One is list type, the other one is string type.

The creation step succeeded.

Then I issue some full text queries to query the node. If the query hits the second property (string type), the record will be returned. If the query only hits the items in the first property (list type), it returns nothing.

So I suspect the full text index does not work for the list type.

Please consider to support the full text index for the list type.

I am not sure about the ordinary index. Maybe it is not a good idea to allow the ordinary index being created on a list type property.

Many thanks.

**Comment by swilly22** [comment]
Both exact-match and full-text indices operate solely on numeric and string values, because RedisGraph doesn't enforce schema you can have 2 different nodes containing the attribute `v` both labeled as `L` but one has `v=1` while the other `v=[1]` when indexing the attribute `v` under the label `L` only numeric and string values will be indexed.

I'm not sure how indexing of a list type would work from the standpoint of the user and the type of criteria a user can issue.

That said, I think it is unlikely that we would support this feature in the near future.
