### ISSUE TITLE
Binary Inputs / Outputs

### ISSUE THREAD

**Issue by victorstewart** [RedisGraph/RedisGraph#1115]
i'm hoping to serialize my inputs before calling my algorithms, and serializing by outputs before returning them... to facilitate more natural structuring and effortless reading.

is there an existing way to pass a binary blob into an algo? I assume not because we're relying on the libcypher parser and have no explicit way to pass a size.

how about returning a binary blob from an algo? I assume this should be much easier as it would just require creating another SIValue type that's able to retrieve its length.

**Comment by jeffreylovitz** [comment]
Hi @victorstewart,

Sorry for the late reply, this slipped through the cracks!

Currently RedisGraph doesn't support binary data, as you noted. This could be changed by extending the SIValue struct as you suggest - we can even make the inner format a Redis string, as that has an encoded length and supports binary blobs.

As you note, you will have problems at the parser level, since Cypher does not have a binary literal type. The range of supported bytes is noted here - https://s3.amazonaws.com/artifacts.opencypher.org/railroad/StringLiteral.html .

You could conceivably extend the GRAPH.QUERY arguments array to pass your binary data in additional arguments, but this would probably require a fair amount of rewriting to function effectively.

This isn't a direction in which RedisGraph plans on extending Cypher right now, but if you want advice on how to implement it yourself, we'd be happy to chat with you!

**Comment by victorstewart** [comment]
@jeffreylovitz 

no worries. I actually ended up writing my own graph database with GraphBLAS lol. I have to do some really specific and complicated real time graph operations on CPU and also subscribe to changes.

It's always a tenth the work to just write your own 2000 lines than to figure out how to weave them into someone else's 50,000 lol. So for a whole bunch of reasons it was the path of least resistance!

**Comment by jeffreylovitz** [comment]
Oh, very cool! Good luck with your project!
