### ISSUE TITLE
Blocking query after fresh start

### ISSUE THREAD

**Issue by fercasgal** [RedisGraph/RedisGraph#1150]
The following sequence of operations makes Redis to block after a fresh start:

1592510570.124839 [0 172.23.0.1:46332] "GRAPH.QUERY" "MyGraph" "CREATE INDEX ON :type1(name)"
1592510570.127674 [0 172.23.0.1:46332] "GRAPH.QUERY" "MyGraph" "CREATE INDEX ON :type2(name)"
1592510570.129003 [0 172.23.0.1:46332] "GRAPH.QUERY" "MyGraph" "MERGE (:type1 {name:'name1'})"
1592510570.131316 [0 172.23.0.1:46332] "GRAPH.QUERY" "MyGraph" "MATCH (node:type1 {name:'name1'}) MERGE (dst1:type2 {name:'name2a'}) MERGE (dst2:type2 {name:'name2b'}) MERGE (node)-[:rel]->(dst1) MERGE (node)-[:rel]->(dst2)"

Interestingly, if the creation of the index for type2 is removed, the query is executed correctly.
It also works, if the MERGE clauses for dst2 are removed instead.

**Comment by jeffreylovitz** [comment]
Hi @fercasgal,

Thanks for the report! I suspect that the problem is a deadlock on one of the indexes (each has an internal mutex), though that scenario is _supposed_ to be impossible.

We'll look into this shortly! In the meantime, I'd recommend just creating the index on `type1` until after data has been constructed.
