### ISSUE TITLE
Explanation for the versioning

### ISSUE THREAD

**Issue by sankarp-kavach** [RedisGraph/RedisGraph#1257]
We are trying to use redisgraph but the versioning system is a bit confusing.

The `milestones` of the project says that https://github.com/RedisGraph/RedisGraph/milestones 2.2 is still not 100% complete and is open. However, we see multiple tags in the releases such as: 2.2.2 and 2.2.3 If 2.2 is still not complete, how can there be 2.2.3 released ? Or is there a different semantics for these version numbers ?

So what is really the stable release as of date that we can rely on, for a sufficient duration ?

**Comment by gkorland** [comment]
2.2.x is still not GA and 2.2.2 is a released candidate, a 2.2.3 second release candidate should be released soon.
2.0.19 is the last official GA.

**Comment by K-Jo** [comment]
@sankarp-kavach in addition to @gkorland, the versioning of modules inside redis doesn't allow to append it with e.g. "-M01" / "-RC1" since it's only an integer numeric value.  Please check the release notes, the first sentence indicates GA status, the last sentence adds notes about which version number was used and lastly GA/non-GA is also indicated with the GitHub "pre-release" flag

**Comment by sankarp-kavach** [comment]
Okay. Thanks.

When 2.2 is finally released, what will be the release tag for it ?

And if there are maintenance updates after 2.2 is released, what will be the tags for it ? Because 2.2.2; 2.2.3 are all already used for pre-GA images.
