### ISSUE TITLE
RedisGraph crash without crash dump on query with many edges to a single node

### ISSUE THREAD

**Issue by mdecuir** [RedisGraph/RedisGraph#1305]
We had a bug in our system where a query was being created with redundant references to the same node types that resulted in a crash of RedisGraph without providing any crash dump. From trying to strip down the query to a point that it shareable, I found that the the crash is happening when I have any single query with many edges to or from the same node, such as the following:

```GRAPH.EXPLAIN graph:example "MATCH (b1)<-[]-(f)-[]->(b2), (b3)<-[]-(f)-[]->(b4), (b5)<-[]-(f)-[]->(b6), (b7)<-[]-(f)-[]->(b8), (b9)<-[]-(f)-[]->(b10), (b11)<-[]-(f)-[]->(b12) RETURN count(distinct(id(f)))"```

When I run the above command, I can see memory usage of RedisGraph rapidly grow until the system runs out of memory and it crashes without a dump. This even happens when running against an empty graph.

Performance wise, up to 8 edges with the central node returns in a negligible amount of time. Adding the 9th edge causes the execution plan to return in 0.56 seconds. The 10th edge bumps the time up to 6.74 seconds but no memory usage increase. At the 11th edge, building the execution plan causes an increase of ~4GB of memory usage and takes over 80 seconds to return. At the 12th edge, all of my system's memory is exhausted and the crash happens.

It also seems worth noting that this is only happening when all of the edges reference the same node. I can add additional edges to any of the other nodes without causing any noticeable increase in resource usage.

**Comment by mdecuir** [comment]
Also worth noting there may be a memory leak going on as well.

After running explain with the query containing 11 edges, the increased memory usage persists even after the explain has completed. While it is running, memory usage is increased by roughly 4GB. After it completes, only about 1GB of memory is reclaimed. As a result, every execution of this same call increases the amount of memory used by RedisGraph by 2-3GB.

**Comment by Sceat** [comment]
Which version of redisgraph are you running ?

**Comment by schwab** [comment]
Mdecuir is on my team.  We are using the docker image  redislabs/redisgraph:latest which has ...

**Comment by DvirDukhan** [comment]
@schwab @mdecuir 
WIP
might take a while though...

**Comment by schwab** [comment]
Thank you.  Note it's not directly blocking us at this point as we don't normally have queries with that level of complexity.  The urgency for a fix is low at this time, and as @mdecuir  noted it was brought to light by a bug in our code we have a fix for.  
However, it could cause issues if our users created a very complex queries and I'd think others may someday run into this as well.

**Comment by mdecuir** [comment]
As @schwab said, we hit this issue due to a bug in our code that has now been fixed. It is theoretically possible for someone to use our app to produce a query that encounters this same problem, but the circumstances under which it would occur should be exceedingly rare. We also could potentially introduce some temporary protections to avoid hitting the problem until it is fixed.

In the short term, the magic number where things start changing is more than 9 edges specified with a single node alias in a single query.

**Comment by DvirDukhan** [comment]
@schwab @mdecuir 
Thanks for clearing this.
Just for the sake of transparency, this bug is caused by our implementation of choosing the best way to calculate the matrices multiplication. In this phase, we (naively) calculate all the possible permutations of matrices multiplications and execute additional duplications of them. The number of permutations is the factorial product of the number of edges. while 9 is somehow considerable (9! = 362880), each additional edge increases the order of magnitude of permutations (12! = 479001600). You see where it is going.
We had an internal discussion on how to solve it and @jeffreylovitz will come up with a design document to be implemented soon.

**Comment by mdecuir** [comment]
Glad to hear you were able to identify what is going on so quickly.

**Comment by schwab** [comment]
I'm bumping this thread as we've started hitting this limitation again.  In this case we have AI that's doing analytical searches against our data and since many of our data sources have > 9 dimensions of node relationships ( ie > 9 node fanout ), the AI has to be limited in how deeply it can search for the patterns.  

Is correcting this issue planned in a future release? If not we may have to go back and re-think our node/edge layouts.

**Comment by swilly22** [comment]
@schwab #1325 should address this issue, the fix is currently available on our `edge` docker image and our `master` branch.
```
docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge
```
(please make sure your local docker cache is clear before running)

Would you be able to verify this fix?

**Comment by mdecuir** [comment]
I just verified the fix locally.  I went up to 15ish edges without seeing any noticeable performance degradation.

**Comment by schwab** [comment]
Thanks so much for tackling this one Roi.  I'll watch for this getting into a release.
