### ISSUE TITLE
Support map datatype

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/RedisGraph#1366]

**Comment by jonaskello** [comment]
I was just about to create a feature request for map type. Glad I did a search first :-). Thank you for working on adding this 👍

**Comment by jonaskello** [comment]
In neo4j playground this code works:

```
:param olle => 'released';
Match (m:Movie) where m['released'] > 2000 RETURN m[$olle]
```

However this does currently not work in redisgraph. Will this work once map datatype is implemented?

**Comment by jeffreylovitz** [comment]
@jonaskello,

RedisGraph uses a different syntax for parameters than Neo4j:
```
GRAPH.QUERY G "CYPHER olle='released' Match (m:Movie) where m['released'] > 2000 RETURN m[$olle]"
1) 1) "m[$olle]"
2) 1) 1) (integer) 2005
```
Using this syntax or any language-specific client should make your query work.

**Comment by jonaskello** [comment]
@jeffreylovitz The problem I have is not really with the parameters, that was just to illustrate how I would like to use it. The problem is using a string to index the node in the `RETURN` clause. I tried this simple query in the redisgraph part of redisinsight:

```
MATCH (a) RETURN a['whatever']

> ERROR
> Type mismatch: expected List but was Node

```
It seems the `a` cannot be indexed with a string, thus my conclusion was that it has to do with support for map types but perhaps this is not correct?

**Comment by jeffreylovitz** [comment]
@jonaskello Sorry for the confusion!

Support for the map type has been introduced on the master branch and the Docker tag `edge`; if you are running RedisGraph from one of these places your syntax should work.

The map datatype has not been included in a new version yet.

**Comment by jonaskello** [comment]
@jeffreylovitz Oh, I did not know it was already available on edge :-). I tried it and can confirm it works with my example above! Thank you!
