### ISSUE TITLE
Redis Graph Disk Persistence Question

### ISSUE THREAD

**Issue by Wajihulhassan** [RedisGraph/RedisGraph#152]
On Redis graph docs it says that RedisGraph also has on-disk persistence functionality. 
My question is can I control which graphs to _spill_ to disk and which graphs to _keep_ in memory?
 
For example, My application has a two graphs. One of them is a very large graph that I want on disk (because it is occasionally queried and cannot fit in the memory) and other one is a smaller/summarized version of this graph I want to store on memory (because it is frequently queried and can fit in the memory).

**Comment by jeffreylovitz** [comment]
Hi @Wajihulhassan ,

RedisGraph has on-disk persistence as implemented by Redis:
https://redis.io/topics/persistence

For RedisGraph, this is a means of providing data durability (in the ACID sense). It allows us to restore graphs into memory, rather than working as an alternative to in-memory operations.

You can maintain separate persistence files for separate graphs, but that wouldn't a viable approach if your large graph can't ever be loaded fully into memory!

**Comment by CatalinAdlerDF** [comment]
Bumping this.

Are there any plans to support working with large datasets that cannot fit into memory; or you just do not want to for whatever reason (cold/hot data)?

Thanks!

**Comment by swilly22** [comment]
@CatalinAdlerDF, at the moment there's no plan for spilling graphs to disk, we try to take the "Redis approach" on this at the moment, but I can see why one would want to unload some graphs to disk.
