### ISSUE TITLE
Floating point numbers truncated

### ISSUE THREAD

**Issue by InverseIntegral** [RedisGraph/RedisGraph#2417]
When I run the following two queries:
```
CREATE (:L {p: 0.08294463157653809})
MATCH (n:L) RETURN n.p
```
The result is:
```
0.0829446315765381
```
This happens with redis-cli and with the Jedis client. I'm trying to extract the exact value stored in the property because I later on use it to match those nodes. Is there some way to increase the precision?

I have also seen that there was a previous issue of that kind #377 which was fixed in #378

**Jedis Version**: 4.2.3
**Redis Version**: 6.2.6
**RedisGraph Version**: 2.8.13
**Operating System**: 5.17.9 Arch Linux

**Comment by LiorKogan** [comment]
@InverseIntegral 

We prefer not to introduce such a fix.

Consider the following code:

```
#include <stdio.h>

int main()
{
    double f = 0.08294463157653809;
    double g = 0.1                ;
    printf("%.15f  %.15g\n", f, g);
    printf("%.16f  %.16g\n", f, g);
    printf("%.17f  %.17g\n", f, g);

    return 0;
}

```
The output is 

```
0.082944631576538  0.1
0.0829446315765381  0.1
0.08294463157653809  0.10000000000000001
```

Introducing a more accurate representation for one value would add artificial error for another value.
This is because an IEEE double [has approximately 15.95 decimal digits](https://stackoverflow.com/a/9999508/171006), so any representation with more than 15 digits can potentially introduce an error.

I think you should printf your values with "%.15g" and then use this representation (or store these values as property values).

**Comment by InverseIntegral** [comment]
Thank you for the detailed explanation. I can see why you would rather not change the current behaviour.
I will find a way to work around this on my side!
