### ISSUE TITLE
Indexes can be created on invalid property names

### ISSUE THREAD

**Issue by LiorKogan** [RedisGraph/RedisGraph#2484]
RedisGraph 2.8.15

The following invalid query is considered valid:

```
GRAPH.QUERY g "CREATE INDEX FOR (p:Person) ON (p.m.n, p.p.q)"
```

Since `m.n` and `p.q` are invalid property names, the command should be rejected.
Currently it creates indexes on properties `n` and `q`.

---

The following invalid queries are considered valid as well:

```
GRAPH.QUERY g "CREATE INDEX FOR (p:Person) ON (a.b)"
GRAPH.QUERY g "CREATE INDEX FOR (p:Person) ON (1.b)"
```

Currently both create an index on property `b`.

**Comment by nafraf** [comment]
Hi, I started a solution for this issue, I think that this can be divided in two parts.
The first part is to solve the errors that can be detected by the parser, changes that were implemented in PR posted above.

The second part is to solve the case of invalid queries due to the use of undefined variables: 
```
GRAPH.QUERY g "CREATE INDEX FOR (p:Person) ON (a.b)"
```
The validation of previous case should be done in Redisgraph. This has not been implemented yet.
