### ISSUE TITLE
Query returns incomplete data when correct label constraint specified along with variable length path

### ISSUE THREAD

**Issue by polygonhell** [RedisGraph/RedisGraph#2849]
This query will return

```
 GRAPH.QUERY g "MATCH (t:Taxonomy)<-[:IsA]-(e), (t) -[:Parent*]-> (p) RETURN DISTINCT p.id, labels(p)"
1) 1) "p.id"
   2) "labels(p)"
2)  1) 1) "1.2.3"
       2) "[Taxonomy]"
    2) 1) "1.2"
       2) "[Taxonomy]"
    3) 1) "1"
       2) "[Taxonomy]"
    4) 1) "1.2.3.10"
       2) "[Taxonomy]"
    5) 1) "1.2.4.1"
       2) "[Taxonomy]"
    6) 1) "1.2.4"
       2) "[Taxonomy]"
    7) 1) "1.8.1"
       2) "[Taxonomy]"
    8) 1) "1.8"
       2) "[Taxonomy]"
    9) 1) "1.9.8"
       2) "[Taxonomy]"
   10) 1) "1.9"
       2) "[Taxonomy]"
   11) 1) "1.9.8.5"
       2) "[Taxonomy]"
   12) 1) "1.9.8.11"
       2) "[Taxonomy]"
   13) 1) "2"
       2) "[Taxonomy]"
   14) 1) "3"
       2) "[Taxonomy]"
```

This should return the exact same thing, but looks to have treated the variable length traverse in the second clause as a only a single step.

```
 GRAPH.QUERY g "MATCH (t:Taxonomy)<-[:IsA]-(e), (t) -[:Parent*]-> (p:Taxonomy) RETURN DISTINCT p.id, labels(p)"

2)  1) 1) "2"
       2) "[Taxonomy]"
    2) 1) "3"
       2) "[Taxonomy]"
    3) 1) "1.2"
       2) "[Taxonomy]"
    4) 1) "1.2.3"
       2) "[Taxonomy]"
    5) 1) "1.2.3.10"
       2) "[Taxonomy]"
    6) 1) "1.2.4"
       2) "[Taxonomy]"
    7) 1) "1.2.4.1"
       2) "[Taxonomy]"
    8) 1) "1.8"
       2) "[Taxonomy]"
    9) 1) "1.8.1"
       2) "[Taxonomy]"
   10) 1) "1.9.8"
       2) "[Taxonomy]"
   11) 1) "1.9.8.5"
       2) "[Taxonomy]"
   12) 1) "1.9.8.11"
       2) "[Taxonomy]"
```

**Comment by polygonhell** [comment]
Note I just verified this is recently broken, the 2.10.5 container behaves correctly, the :latest version is broken

**Comment by polygonhell** [comment]
Closing this it was broken and manually pulling the latest image seems to have resolved it

**Comment by DanielNinchev** [comment]
> Note I just verified this is recently broken, the 2.10.5 container behaves correctly, the :latest version is broken

https://github.com/RedisGraph/RedisGraph/issues/2848

It appears that it is still not working for me. Consider the following path:

(a)-[:X]->(b)-[:Y]->(c)-[:Z]->(d)

In this case, last week I would be able to write the following query:
MATCH (a)-[:Z*]->(d) RETURN count(d)
and it would work - I would get the count of the (d) nodes which are under the (a) nodes and have a :Z relationship somewhere in the path several hops away (not with a direct relationship between (a) and (d)).

Now in order to get a valid result, the path needs to have only :Z edges: (a)-[:Z]->(b)-[:Z]->(c)-[:Z]->(d)
It didn't behave that way before. It would work even if there was no (a)-[:Z]->(d) in the graph.

**Comment by LiorKogan** [comment]
@DanielNinchev 
Note that when doing `MATCH (a)-[:Z*]->(d) RETURN count(d)` you are not matching `a` with the `a` created about, but with the `c` created above.

Try the following:
```
GRAPH.QUERY g "create (a:A)-[:X]->(b:B)-[:Y]->(c:C)-[:Z]->(d:D)"

GRAPH.QUERY g "MATCH (a)-[:Z*]->(d:D) RETURN count(d)"
1) 1) "count(d)"
2) 1) 1) (integer) 1

GRAPH.QUERY g "MATCH (a:A)-[:Z*]->(d:D) RETURN count(d)"
1) 1) "count(d)"
2) 1) 1) (integer) 0

```

**Comment by DanielNinchev** [comment]
> @DanielNinchev Note that when doing `MATCH (a)-[:Z*]->(d) RETURN count(d)` you are not matching `a` with the `a` created above, but with the `c` created above.
> 
> Try the following:
> 
> ```
> GRAPH.QUERY g "create (a:A)-[:X]->(b:B)-[:Y]->(c:C)-[:Z]->(d:D)"
> 
> GRAPH.QUERY g "MATCH (a)-[:Z*]->(d:D) RETURN count(d)"
> 1) 1) "count(d)"
> 2) 1) 1) (integer) 1
> 
> GRAPH.QUERY g "MATCH (a:A)-[:Z*]->(d:D) RETURN count(d)"
> 1) 1) "count(d)"
> 2) 1) 1) (integer) 0
> ```

Yes, I understand that. What I actually meant that in the following path:
(a:A)-[:X]->(b:B)-[:Y]->(c:C)-[:Z]->(d:D)
I was able to do the following before:
GRAPH.QUERY g "MATCH (a:A)-[:Z*]->(d:D) RETURN count(d)"
 and actually count the :D nodes which are under :A and have :Z relationship somewhere in the path. Now, in order to do so, I have to name all the relationships in the considered path to be :Z, like this;
 
MATCH (a:A)-[:Z]->(b:B)-[:Z]->(c:C)-[:Z]->(d:D)
RETURN cound(d)

Is that the intended behaviour? Is it necessary all the edges on the path to have the same type in order for the syntax [:EDGE*] to work correctly? If that is so, I wonder how did it work for me before... I have read the Cypher Query Language version 9 book, but there is no given example where the types of relationships in a path are different and the syntax [:EDGE*] is being used.

@polygonhell  could you give your opinion about that? How do you understand the [:EDGE*] syntax and did you use it with the same intention as me?

**Comment by LiorKogan** [comment]
@DanielNinchev 
The current behavior is the correct one. 

Trivially, you can do 
```
GRAPH.QUERY g "MATCH (a:A)-[*]->(d:D) RETURN count(d)"
1) 1) "count(d)"
2) 1) 1) (integer) 1
```

**Comment by DanielNinchev** [comment]
> @DanielNinchev The current behavior is the correct one.
> 
> Trivially, you can do
> 
> ```
> GRAPH.QUERY g "MATCH (a:A)-[*]->(d:D) RETURN count(d)"
> 1) 1) "count(d)"
> 2) 1) 1) (integer) 1
> ```

This is true, but the problem is, that I have to use count(DISTINCT d), which is slower, because there are several relationships between the (:C) and (:D) nodes. Currently I am using the following:
MATCH (a:A)-[*]->(d:D) 
RETURN count(DISTINCT d)
but it is slower than the syntax I was using before.

**Comment by LiorKogan** [comment]
Can you revert to the previous version and check?

**Comment by DanielNinchev** [comment]
We already discovered this issue on 2.10.4. version. Literally it was working on 2.10.4. and one day it stopped working without us making any changes on the graph or updating the version. After we found out about the problem and I saw this issue here being raised by @polygonhell , I decided to update to 2.10.5. to check if that will fix it like he says. It doesn't for me. I know this sounds absurd. Hence, now I think we probably deluded ourselves - maybe the [:EDGE*] syntax never worked as we thought it should and we had some changes made in the graph that were unknown to us and that made it possible to work. But I would like to see if @polygonhell confirms that he had the same issue as me and fixed it somehow.

**Comment by polygonhell** [comment]
My understanding of the edge syntax is that should return 0
given 
```
(a:A)-[:X]->(b:B)-[:Y]->(c:C)-[:Z]->(d:D)
```
The query
```
GRAPH.QUERY g "MATCH (a:A)-[:Z*]->(d:D) RETURN count(d)
```
Will only look over Z edges, so there is no match, if it worked previously I think it was previously broken.

You can do this
```
GRAPH.QUERY g "MATCH (a:A)-[:Z|Y|X*]->(d:D) RETURN count(d)
```
or as suggested 
```
GRAPH.QUERY g "MATCH (a:A)-[*]->(d:D) RETURN count(d)
```

That's at least my understanding of the syntax, as I read the spec.

**Comment by DanielNinchev** [comment]
Thank you for the response. It appears that I misunderstood the syntax. I am closing my issue.
