### ISSUE TITLE
Way to prevent cycles

### ISSUE THREAD

**Issue by bwf93** [RedisGraph/RedisGraph#285]
Is there anyway to detect and prevent cycles in match queries with what is currently implemented in cyper?  I have a query 
`MATCH (n:person)-[:related*1]->(p) where n.identifier='1' return p`

The node 1 is connected to 499 other nodes that are all connected to each other when I change the query to 
`MATCH (n:person)-[:clustered*2]->(p) where n.ire='Occupancies:83.Person[1]' return p`
every node is returned twice and the query 
`MATCH (n:person)-[:clustered*1..]->(p) where n.ire='Occupancies:83.Person[1]' return p`
runs forever.  Is there a way to limit the query to stop a traversal if a previously visited node is visited again?

**Comment by swilly22** [comment]
Hi @bwf93 
Short answer:
it depends on are the query, if the execution plan uses decides on using `Conditional Traverse` then no, otherwise `Conditional Variable Length Traverse` is used and cycles are detected.

Long answer:
When executing a query with a variable length path as you've specified:
`MATCH (n:person)-[:clustered*1..]->(p) where n.ire='Occupancies:83.Person[1]' return p`

RedisGraph will execute a DFS like algorithm, [see all_paths.c](https://github.com/RedisLabsModules/RedisGraph/blob/master/src/algorithms/all_paths.c#L44)

The DFS traversal will expand the current path only if the node being visited isn't already on the path
[see condition](https://github.com/RedisLabsModules/RedisGraph/blob/master/src/algorithms/all_paths.c#L77)

In the case of: `MATCH (n:person)-[:clustered*2]->(p) where n.ire='Occupancies:83.Person[1]' return p` because `[:clustered*2]` specifies a constant length 2, RedisGraph will use matrix multiplication instead of DFS, in which there's no validation for visited nodes.

That said, I've ran this small example:
A is connected to B,C,D.
B,C,D and interconnected.

`GRAPH.QUERY G "create (a {val:1}), (b {val:2}), (c {val:3}), (d {val:4}), (a)-[:connected]->(b), (a)-[:connected]->(c), (a)-[:connected]->(d), (b)-[:connected]->(c), (a)-[:connected]->(d), (c)-[:connected]->(b), (c)-[:connected]->(d), (d)-[:connected]->(c), (d)-[:connected]->(b)"`

Find all reachable nodes from A 2 hops away,
`GRAPH.QUERY G "match (a {val:1})-[*2]->(p) return p"`

```
127.0.0.1:6379> GRAPH.QUERY G "match (a {val:1})-[*2]->(p) return p"
1) 1) 1) "p.val"
   2) 1) "4.000000"
   3) 1) "2.000000"
   4) 1) "3.000000"
```

Lastly regarding:
`MATCH (n:person)-[:clustered*1..]->(p) where n.ire='Occupancies:83.Person[1]' return p`

I'm not sure who node n is connected to, but `[:clustered*1..]` has no limit on the path length, in which case given your graph structure, there are 499 factorial different paths to investigate, which will take forever to compute.
