### ISSUE TITLE
Centos7 installation error

### ISSUE THREAD

**Issue by 980849920** [RedisGraph/RedisGraph#287]
/cdb/RedisGraph-1.0.7/src/module.c: 在函数‘RedisModule_OnLoad’中:
/cdb/RedisGraph-1.0.7/src/module.c:60:5: 警告：隐式声明函数‘_Generic’ [-Wimplicit-function-declaration]
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
In file included from /cdb/RedisGraph-1.0.7/src/arithmetic/../execution_plan/../graph/entities/graph_entity.h:12:0,
                 from /cdb/RedisGraph-1.0.7/src/arithmetic/../execution_plan/../graph/entities/node.h:12,
                 from /cdb/RedisGraph-1.0.7/src/arithmetic/../execution_plan/record.h:12,
                 from /cdb/RedisGraph-1.0.7/src/arithmetic/arithmetic_expression.h:11,
                 from /cdb/RedisGraph-1.0.7/src/module.c:18:
/cdb/RedisGraph-1.0.7/src/arithmetic/../execution_plan/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:2859:13: 错误：expected expression before ‘int’
             int              : GxB_Global_Option_set ,  \
             ^
/cdb/RedisGraph-1.0.7/src/module.c:60:5: 附注：in expansion of macro ‘GxB_set’
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
/cdb/RedisGraph-1.0.7/src/arithmetic/../execution_plan/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:2859:13: 错误：expected expression before ‘int’
             int              : GxB_Global_Option_set ,  \
             ^
/cdb/RedisGraph-1.0.7/src/module.c:61:5: 附注：in expansion of macro ‘GxB_set’
     GxB_set(GxB_HYPER, GxB_NEVER_HYPER); // matrices are never hypersparse
     ^
make[1]: *** [/cdb/RedisGraph-1.0.7/src/module.o] 错误 1
make[1]: 离开目录“/cdb/RedisGraph-1.0.7/src”
===================================================================

When I compiled the centos7, I got an error. I don't know how to solve it.

**Comment by swilly22** [comment]
Hey @980849920 

I've tried compiling on CentOS Linux release 7.6.1810 (Core)
using gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

`root@e3421223e377 RedisGraph]# make
make -C ./src all
make[1]: Entering directory `/RedisGraph/src'
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"/RedisGraph/src" -DREDIS_MODULE_TARGET -g -ggdb -O3  -c /RedisGraph/src/value.c -o /RedisGraph/src/value.o -MMD -MF /RedisGraph/src/value.d
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"/RedisGraph/src" -DREDIS_MODULE_TARGET -g -ggdb -O3  -c /RedisGraph/src/config.c -o /RedisGraph/src/config.o -MMD -MF /RedisGraph/src/config.d
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"/RedisGraph/src" -DREDIS_MODULE_TARGET -g -ggdb -O3  -c /RedisGraph/src/module.c -o /RedisGraph/src/module.o -MMD -MF /RedisGraph/src/module.d
/RedisGraph/src/module.c: In function 'RedisModule_OnLoad':
/RedisGraph/src/module.c:60:5: warning: implicit declaration of function '_Generic' [-Wimplicit-function-declaration]
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
In file included from /RedisGraph/src/arithmetic/../execution_plan/../graph/entities/graph_entity.h:12:0,
                 from /RedisGraph/src/arithmetic/../execution_plan/../graph/entities/node.h:12,
                 from /RedisGraph/src/arithmetic/../execution_plan/record.h:12,
                 from /RedisGraph/src/arithmetic/arithmetic_expression.h:11,
                 from /RedisGraph/src/module.c:18:
/RedisGraph/src/arithmetic/../execution_plan/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:2859:13: error: expected expression before 'int'
             int              : GxB_Global_Option_set ,  \
             ^
/RedisGraph/src/module.c:60:5: note: in expansion of macro 'GxB_set'
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
/RedisGraph/src/arithmetic/../execution_plan/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:2859:13: error: expected expression before 'int'
             int              : GxB_Global_Option_set ,  \
             ^
/RedisGraph/src/module.c:61:5: note: in expansion of macro 'GxB_set'
     GxB_set(GxB_HYPER, GxB_NEVER_HYPER); // matrices are never hypersparse
     ^
make[1]: *** [/RedisGraph/src/module.o] Error 1
make[1]: Leaving directory `/RedisGraph/src'
make: *** [all] Error 2`

The problem is that  `_Generic` is only supported from GCC 4.9
Please upgrade GCC to 4.9 or above.

**Comment by 980849920** [comment]
Hi @swilly22 

Thank you for your reply, but I still have to bother you again, because my gcc version is still upgraded to gcc 5.1, so whether compiling can only support gcc 4.9 version.

**Comment by jeffreylovitz** [comment]
@980849920 , when using GCC 5.1 are you getting the exact same errors as you posted originally? If not, it is possible that a different dependency is missing out of date.

For example, CMake should be at least v3.0, and `m4` is required for compilation.

Feel free to send further error logs!

**Comment by 980849920** [comment]
@jeffreylovitz 

I think so, all the mistakes are the same. I tried three versions of gcc in 4.9.0, 4.9.4, and 5.1.0. But the errors I see are consistent.
At the same time, my system version is: 
Linux docker-master 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
//  CentOS Linux release 7.4.1708 (Core) 


![image](https://user-images.githubusercontent.com/31610078/50322720-4b743280-0511-11e9-86a7-aa83953e3437.png)

**Comment by Zhouchuanwen** [comment]
> @jeffreylovitz
> 
> I think so, all the mistakes are the same. I tried three versions of gcc in 4.9.0, 4.9.4, and 5.1.0. But the errors I see are consistent.
> At the same time, my system version is:
> Linux docker-master 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> // CentOS Linux release 7.4.1708 (Core)
> 
> ![image](https://user-images.githubusercontent.com/31610078/50322720-4b743280-0511-11e9-86a7-aa83953e3437.png)

Me too...So...how to solve it ?

**Comment by jeffreylovitz** [comment]
@Zhouchuanwen @980849920
Sorry, I haven't had the chance to dig into this yet! I'll bump it up in our priorities and find a resolution soon.

**Comment by collisonchris** [comment]
Trying to build this on centos7 as well, seeing the same issues as @980849920 

```
make[1]: Entering directory `/home/<user>/RedisGraph/src'
    CC /home/<user>/RedisGraph/src/module.o
/home/<user>/RedisGraph/src/module.c: In function ‘RedisModule_OnLoad’:
/home/<user>/RedisGraph/src/module.c:51:5: warning: implicit declaration of function ‘_Generic’ [-Wimplicit-function-declaration]
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
In file included from /home/<user>/RedisGraph/src/arithmetic/../graph/entities/graph_entity.h:11:0,
                 from /home/<user>/RedisGraph/src/arithmetic/../graph/entities/node.h:11,
                 from /home/<user>/RedisGraph/src/arithmetic/../graph/query_graph.h:10,
                 from /home/<user>/RedisGraph/src/arithmetic/arithmetic_expression.h:12,
                 from /home/<user>/RedisGraph/src/module.c:16:
/home/<user>/RedisGraph/src/arithmetic/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:3090:13: error: expected expression before ‘int’
             int              : GxB_Global_Option_set ,  \
             ^
/home/<user>/RedisGraph/src/module.c:51:5: note: in expansion of macro ‘GxB_set’
     GxB_set(GxB_FORMAT, GxB_BY_COL); // all matrices in CSC format
     ^
/home/<user>/RedisGraph/src/arithmetic/../graph/entities/../../../deps/GraphBLAS/Include/GraphBLAS.h:3090:13: error: expected expression before ‘int’
             int              : GxB_Global_Option_set ,  \
             ^
/home/<user>/RedisGraph/src/module.c:52:5: note: in expansion of macro ‘GxB_set’
     GxB_set(GxB_HYPER, GxB_NEVER_HYPER); // matrices are never hypersparse
     ^
make[1]: *** [/home/<user>/RedisGraph/src/module.o] Error 1
make[1]: Leaving directory `/home/<user>/RedisGraph/src'
make: *** [all] Error 2
```

Anyone find a workaround or things to try to help resolve this to get going on centos7?

**Comment by swilly22** [comment]
Please see [CentOS dockerfile](https://github.com/RedisGraph/RedisGraph/blob/master/Dockerfile.centos) as a reference
