### ISSUE TITLE
Why update operations are slow

### ISSUE THREAD

**Issue by zhangliang-zl** [RedisGraph/RedisGraph#2909]
When there are slow query statements. All write operations will also be slow.

Will the read statement block the write operation?

When this happens, a certain CPU spikes to 95+%.
My configuration already takes advantage of multiple CPU cores, but it looks like writes are blocked

Is there any relevant documentation？

**Comment by LiorKogan** [comment]
Each query in RedisGraph is classified as a read-only query (“reader”) or a write query (“writer”). 

RedisGraph enforces writer/readers separation by using a lock so that either multiple readers can acquire the lock, or just a single writer. As long as a writer is executing, no other query can acquire the lock, and as long as a reader is executing, no writer can obtain the lock.

**Comment by zhangliang-zl** [comment]
Will write operations have higher priority? One slow query that blocks all writes?

**Comment by LiorKogan** [comment]
Writes are prioritized over reads, but all currently-executing reads need to terminate before the write starts.
