### ISSUE TITLE
Is there any method to bulk upload relationship between existing node

### ISSUE THREAD

**Issue by sandyk12** [RedisGraph/RedisGraph#332]
is there any method to create a relationship between existing node using bulk.
 query="
MATCH (u:person {name:'y2'}), (r:person {name:'y200'}) CREATE (u)-[:friend]->(r)
MATCH (u:person {name:'y2'}), (r:person {name:'y200'}) CREATE (u)-[:friend]->(r)
MATCH (u:person {name:'y3'}), (r:person {name:'y100'}) CREATE (u)-[:friend]->(r),
MATCH (u:person {name:'y4'}), (r:person {name:'y200'}) CREATE (u)-[:friend]->(r)"

**Comment by swilly22** [comment]
Incase you're at the stage of initially creating your graph (which I don't think you are) then use [redisgraph-bulk-loader](https://github.com/RedisLabsModules/redisgraph-bulk-loader)

Otherwise, probably not, but please note that a writer will hardly effect your readers, as a write query will only lock the database for its commit phase.

**Comment by sandyk12** [comment]
Can we use this type of query in redisgraph

{ batch : [{"1":334,"2":222,3:3840, ... 100k}]}
WITH {batch} as data, [k in keys({batch}) | toInt(k)] as ids
MATCH ()-[rel]->() WHERE id(rel) IN ids
SET rel.foo = data[toString(id(rel))] // single property
SET rel= data[toString(id(rel))] // all properties

**Comment by gkorland** [comment]
ref #380

**Comment by swilly22** [comment]
The map datatype isn't supported at the moment.

**Comment by gkorland** [comment]
ref https://github.com/RedisGraph/RedisGraph/issues/1366
