### ISSUE TITLE
Shortest path

### ISSUE THREAD

**Issue by Talha-B** [RedisGraph/RedisGraph#440]
Hi,

I am new to RedisGraph and graph databases in general. With Neo4j, I've seen that there is a function that allows us to calculate the shortest path between source and destination nodes. It does not seem like this is possible in RedisGraph and from what I can gather, the Cipher query language that is implemented by RedisGraph does not have full functionality that might allow the creation of such functions.

Is there a plan for this to be introduced?

**Comment by K-Jo** [comment]
Hi @Talha-B this is currently not supported.  We added it to the backlog and keep you updated here when it gets prioritised

**Comment by timd73** [comment]
I'm also interested in seeing shortestPath in redis-graph - adding my +1 vote.

**Comment by ValkyrieUK** [comment]
Is there any update on this? Would really like to use this but not having shortest path pretty much stops me doing so.

**Comment by swilly22** [comment]
#1015

**Comment by meena-uptycs** [comment]
Any progress on this ? What is the difference between this and shortestPath in https://github.com/RedisGraph/RedisGraph/blob/master/tests/flow/test_shortest_path.py

**Comment by jeffreylovitz** [comment]
Hi @meena-uptycs,

`shortestPath` has been implemented as described here - https://oss.redislabs.com/redisgraph/commands/#shortestpath.

Since this function is invoked with a known source and destination, it does not use Dijkstra's algorithm. It instead uses a push-pull BFS algorithm, the implementation of which can be found here - https://github.com/RedisGraph/RedisGraph/blob/master/src/algorithms/LAGraph_bfs_pushpull.c.
