### ISSUE TITLE
Find by indexed id is very slow if multiple ids are specified using 'WHERE' + 'OR' combination

### ISSUE THREAD

**Issue by WitchsCat** [RedisGraph/RedisGraph#480]
If multiple ids are specified in a WHERE clause using an OR separator, this causes the query to become as slow as if it isn't using any indexes. On big data sets the difference is up to 100 times

**Comment by jeffreylovitz** [comment]
Hi @WitchsCat,

The current indexing implementation is limited in that it does not handle disjoint (`!=`) and `OR` filters. Your query is probably generating a label scan rather than an index scan, which you can verify with the `GRAPH.EXPLAIN` command:
```
$ redis-cli GRAPH.EXPLAIN social "MATCH (p:person) WHERE p.id < 5 RETURN p"
"Results\n    Project\n        Index Scan\n"
$ redis-cli GRAPH.EXPLAIN social "MATCH (p:person) WHERE p.id < 5 OR p.id > 10 RETURN p"
"Results\n    Project\n        Filter\n            Node By Label Scan\n"
```

We're currently working on a new index implementation, which I expect will be complete in about 2 months. The new implementation already resolves the disjoint limitation; I'm not sure if its current form resolves the `OR` limitation. Regardless, support for this is definitely on the roadmap!

**Comment by WitchsCat** [comment]
Thanks for a quick reply. Really looking forward to it.
Networking is taking some time when for a 10 ids it is faster to do "MATCH (c:Claim{id:'1'}) RETURN c" (takes less than 1 ms) 10 times,
rather than to get a reply for "MATCH (c:Claim) WHERE c.id = '1' OR c.id = '2' OR c.id = '3' .... RETURN c" (takes 300ms for 10 ids) 

and there is an index on Claim.id. Especially painful it gets when our graph started to have a 1 000 000 plus Claim Objects. 

Could you consider getting a special handling for such a simple case?
This bit me quite hard on scale, and maybe I was too dumb but couldn't find this in the 'OR' description that it skips indexes, would be really useful to add it there.

**Comment by jeffreylovitz** [comment]
This should be documented in [Known Limitations](https://oss.redislabs.com/redisgraph/known_limitations/), and is not! Sorry about that - I'll update the documentation shortly.

The cause of the limitation is that indexes are currently implemented as skip lists, and when a query specifies indexed properties in a WHERE clause we check to see if we're we can traverse the skip list with a lower and/or upper bound. `WHERE c.id = 1` provides both, so the lookup only takes log(n) time.

We haven't added heuristics for determining bounds when an `OR` filter is provided - it's a good idea, but  a good number of edge cases get introduced. I wouldn't want to spend the time adding that right now, since the skiplist implementation is on the way out.

There are a few workarounds that may be helpful for you:
`MATCH (c:Claim) WHERE c.id >=1 AND c.id <= 3 .... RETURN c`
If this is an option for your use case, it would be the ideal!

`MATCH (c:Claim) WHERE c.id > 0 AND (c.id = 1 OR c.id = 2 OR c.id = 3) .... RETURN c`
This looks a little silly, but the first filter will cause an index scan to be created. This is likely to improve performance, though it's dependent on your data.

``MATCH (c:Claim) WHERE c.id = 1 OR c.id = 2 OR c.id = 3 .... RETURN  c LIMIT 3`
Since the `id` property isn't guaranteed to be unique, we need to check every matching entity, so it's an O(n) operation. If you trust `id` to be unique, you can add a `LIMIT` clause that lets the module know the max number of results it should look for.

It seems like you're trying to paginate results, so you may be able to use the `ID()` function that is optimized for some cases similar to this:
`MATCH (c:Claim) WHERE ID(c) > 0 AND ID(c) <= 3 .... RETURN c`
This seeks on RedisGraph internal IDs, which is a very fast operation, though I think it suffers the same `OR` limitation.

I'd be happy to provide more suggestions if you can give additional details about your use case and queries!

**Comment by WitchsCat** [comment]
@jeffreylovitz 
I will try the "silly" option
MATCH (c:Claim) WHERE c.id > 0 AND (c.id = 1 OR c.id = 2 OR c.id = 3) .... RETURN c
This looks a little silly, but the first filter will cause an index scan to be created. This is likely to improve performance, though it's dependent on your data.

Thanks a lot!

**Comment by jeffreylovitz** [comment]
@WitchsCat Great! I'd recommend adding the `LIMIT` clause as well if you know the number of records you're interested in (which in these examples you do); it should be a big help at scale.

**Comment by WitchsCat** [comment]
@jeffreylovitz wow, the limit clause caused a huge difference

for 2 ids

NO LIMIT -> 1) "Query internal execution time: 175.264340 milliseconds"
WITH LIMIT -> 1) "Query internal execution time: 0.219105 milliseconds"

**Comment by WitchsCat** [comment]
@jeffreylovitz worked for some ids, but doesn't work for the others especially, if one of the ids doesn't exist in the graph.

Is there a way maybe to use UNWIND, and just loop through the solo ids with match on the redisgraph side and than collect the results into a single list and give it back?

**Comment by swilly22** [comment]
We've replaced our index with RediSearch, with that the index can be utilised when the indexed property is used in an `OR` condition.
