### ISSUE TITLE
Unique constraint on an attribute

### ISSUE THREAD

**Issue by WitchsCat** [RedisGraph/RedisGraph#489]
I can't use MERGE in my use case, is there any way on the road map to add a Unique constraint?

In my case I'm creating a lot of duplicates if something goes wrong, and body of the nodes contain a creation date, so MERGE won't work

**Comment by swilly22** [comment]
Hi @WitchsCat,
We haven't gave much thought to unique constraint, let me consult with the team and we'll update here.

**Comment by amitsharma8891** [comment]
I am also facing the same issue, lots of duplicate records(node). In my case, data integrity is very important the same user gets created multiple time.

**Comment by swilly22** [comment]
@amitsharma8891 
Can't you use `Merge` to avoid duplicates?

**Comment by amitsharma8891** [comment]
Thanks for your response, earlier I tried using but the problem with Merge is if a small change in property instead of updating the same node with the same user_id it created a new Node.

```
user = Node(label='User', properties={'user_id':'someid','name': 'helloo'})  
user = Node(label='User', properties={'user_id':'someid','name': 'hell'})   # -- This creates new node 
```instead updating the 'someid' node

This causes a major issue and couldn't continue

Thanks

**Comment by swilly22** [comment]
I see your point, currently the only solution I can think of is finding out if a User node with a given `user_id` already exists (create an index over User:user_id) if it does, then you can update/add properties to it, otherwise you would have to create it.

**Comment by amitsharma8891** [comment]
Thanks for your response. Do you have any roadmap to introduce unique constraints?

**Comment by swilly22** [comment]
Come to think of it, you might be able to use both MERGE and SET,
`MERGE` on user_id and `SET` name.

**Comment by flpgrz** [comment]
_RedisGraph v2.0.15_

Any news concerning the support of UNIQUE CONSTRAINTs?

I was try to running this but it fails:
`CREATE CONSTRAINT node_id ON (n:Node) ASSERT n.id IS UNIQUE`

This is normally working on Neo4J - so I was wondering if maybe you support a different syntax, or if the feature is simply not available at the moment.
Thanks.

**Comment by jeffreylovitz** [comment]
@flpgrz We have not introduced support for any constraints as yet! It's a feature request we've heard from a few users, but introducing schema impositions would be a significant change for RedisGraph, so I'm not sure where it will fall upon our roadmap currently.

**Comment by Joshuaalbert** [comment]
Any progress on this in that last 1.5 years? Constraints would be useful for us too.

**Comment by swilly22** [comment]
@LiorKogan are constraints on our near future map ?

**Comment by LiorKogan** [comment]
We have a request from Verifone (see
https://redislabs.atlassian.net/browse/PM-1063)
It is not currently on our roadmap, but we may prioritize it - if we won't
close the Apple deal.

**Comment by LiorKogan** [comment]
Constraints are not currently prioritized.

**Comment by jgaskins** [comment]
Just a note for others coming to this issue. I thought I had a use case where a constraint was needed — I need to abort a nontrivial query if a node with this same property value already exists, but I've discovered a couple workarounds:

In simple cases where you only need to detect whether `MERGE ... ON CREATE` created the node, you can check for the `Nodes created: X` metadata in the result.

For the use case that brought me here, I was creating other nodes within the query and I need to avoid creating any of them if that one node already exists — specifically, I was creating a user account and a bunch of related data that other parts of the app expect. I had 2 workarounds that I could see:

1. Use `MERGE ... ON CREATE` for every node that would be created in the query
2. Use `SET NodeLabel:property:value 1 NX EX 10` as an expiring mutex lock before running the `MERGE` query and return a failure result if that query returns `nil`.

I ended up choosing option 2 because it made my query easier to grok but if you have a lot of different code paths that can create this particular node, that might get unwieldy. Honestly, constraints would be an ideal fail-fast solution, but if they're not feasible for the team right now, hopefully one of these workarounds will help.

**Comment by jdgamble555** [comment]
Is this still not a priority?  I'm not sure why such an important feature is at the bottom of this list for a database?

J

**Comment by LiorKogan** [comment]
Planned for the first half of 2023.

**Comment by jdgamble555** [comment]
@LiorKogan - Hey Lior, is this still planned for this quarter? I didn't see it on the [backlog](https://github.com/RedisGraph/RedisGraph/projects/8).  I'm not sure if you guys have an official roadmap anywhere? 

Since internal ID types are [not indexed](https://github.com/RedisGraph/RedisGraph/issues/1984), another use case would be to enforce unique ID properties.

Thanks!

J

**Comment by LiorKogan** [comment]
@jdgamble555 
Yes, it is still planned for H1. 

Developed under the [unique_constraint](https://github.com/RedisGraph/RedisGraph/tree/unique_constraint) branch.

We don't maintain a public roadmap because our priorities can change due to commercial considerations.

Constraints indeed open the door to many possible optimizations.

We also consider adding `mandatory` constraint next.

**Comment by hpvd** [comment]
@LiorKogan awesome!

Since the linked branch seems not to be available anymore (404),
can you already give a hint what kind of constraints we can look forward to?

e.g. other work with these 4 types of constraints to help with data integrity/ quality
1. Unique node property constraints
2. Node property existence constraints
3. Relationship property existence constraints
4. Node key constraints
more details
https://neo4j.com/docs/cypher-manual/current/constraints/

**Comment by LiorKogan** [comment]
All of the above.

Upcoming commands in 2.12; already available in this pre-release version: https://github.com/RedisGraph/RedisGraph/releases/tag/v2.12.0

New commands documentation:

https://redis.io/commands/graph.constraint-create/
https://redis.io/commands/graph.constraint-drop/

**Comment by hpvd** [comment]
prefect!
Many tanks for hint, your work and the provided links!
