### ISSUE TITLE
[cypher] [enhancement] support for count(*)

### ISSUE THREAD

**Issue by wis** [RedisGraph/RedisGraph#501]
``` > GRAPH.QUERY MotoGP "MATCH () RETURN count()"``` works, but 
``` > GRAPH.QUERY MotoGP "MATCH () RETURN count(*)"```
returns syntax error near '*'

[cypher spec](https://github.com/opencypher/openCypher/search?q=RETURN+count%28*%29&unscoped_q=RETURN+count%28*%29)

**Comment by jeffreylovitz** [comment]
@wis Thanks for opening this issue!

We're in the process of switching to a new parser (#454), which will eliminate the burden of creating new rules for every syntax case. Once that's done (estimating ~4 weeks), we should be able to achieve Cypher compliance for nuances like this quite quickly.

Since `MATCH () RETURN count(*)` is functionally equivalent to a query like `MATCH (a) RETURN count(a)`, I don't think it would be worthwhile to make this change prior to finishing the parser replacement, but it should be added quickly after (if not with) the closure of #454. Let me know if I'm overlooking some functionality of `COUNT(*)`, though!

**Comment by swilly22** [comment]
```
GRAPH.explain MotoGP "MATCH () RETURN count(*)"
1) "Results"
2) "    Aggregate"
3) "        All Node Scan | (anon_0)"
```
