### ISSUE TITLE
tck tests server crash

### ISSUE THREAD

**Issue by DvirDukhan** [RedisGraph/RedisGraph#526]
1. Scenario: Matching using a relationship that is already bound  # features/MatchAcceptance2.feature:1014
memory re-release
query:
`MATCH ()-[r1]->()
      WITH r1 AS r2
      MATCH ()-[r2]->()
      RETURN r2 AS rel`
2. Scenario: Fail when using property access on primitive type            # features/MatchAcceptance2.feature:1289
query:
`MATCH (n)
      WITH n.prop AS n2
      RETURN n2.prop`
3. Scenario: Accept valid Unicode literal  # features/ReturnAcceptance2.feature:93
query:
`RETURN '\u01FF' AS a`
4. Scenario: Using aliased DISTINCT expression in ORDER BY  # features/ReturnAcceptance2.feature:360 Assertion failed: (false), function Record_Hash64, file /Users/dvirdukhan/Code/RedisGraph/src/execution_plan/record.c, line 215
query:
`CREATE ({id: 1}), ({id: 10})
MATCH (n)
      RETURN DISTINCT n.id AS id
        ORDER BY id DESC
`

5. Scenario: Aliasing expressions  # features/ReturnAcceptance2.feature:407
query:
`MATCH (a)
      RETURN a.id AS a, a.id`

6. Scenario: Return a single-quoted string  # features/Literals.feature:76
query:
`RETURN '' AS literal`

7. Scenario: Return a double-quoted string  # features/Literals.feature:86
memory re-release
query:
`RETURN "" AS literal`

8. Scenario: Return an integer  # features/Literals.feature:36
memory re-release
query:
`RETURN 1 AS literal`

**Comment by jeffreylovitz** [comment]
1) now a validation error:
`(error) Reusing the WITH projection 'r2' in another pattern is currently not supported`
Using WITH-projected entities in subsequent QueryGraphs requires some updates to QueryGraph logic.

2) This scenario is supposed to raise a `PropertyAccessOnNonMap` TypeError, but we don't have strong error handling for this scenario (or a strong conception of maps). Currently we just return NULL in this scenario, which is a non-ideal fix:
https://github.com/RedisGraph/RedisGraph/blob/master/src/arithmetic/arithmetic_expression.c#L290-L292

3) No crash, but still a skip, since we return the code points instead of rendering the Unicode.

4) No crash, but still a skip. This query relies on operations being executed in sequence, whereas we process the `MATCH` clause prior to the `CREATE` at present.

5-8 all pass, and are no longer skipped.
