### ISSUE TITLE
Floats being returned as strings.

### ISSUE THREAD

**Issue by LWprogramming** [RedisGraph/RedisGraph#553]
According to the Open Cypher [language specification](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf), integers and floats are both supported. However, floats seem to be getting converted into strings.

```python
>>> import redis
>>> r = redis.Redis()
>>> r.execute_command('GRAPH.QUERY animals', 'CREATE (n {test_field: 1234})')
[[], [b'Nodes created: 1', b'Properties set: 1', b'Query internal execution time: 0.497528 milliseconds']]
>>> r.execute_command('GRAPH.QUERY animals', 'CREATE (n {test_field: 1234.567})')
[[], [b'Nodes created: 1', b'Properties set: 1', b'Query internal execution time: 0.219208 milliseconds']]
>>> from redisgraph import Graph
>>> rg = Graph('animals', r)
>>> rg.query('MATCH (n) RETURN n').pretty_print()
+-----------------+
| b'n.test_field' |
+-----------------+
|       1234      |
|   b'1234.567'   |
+-----------------+

b'Query internal execution time: 0.622010 milliseconds'
```

Is this the intended behavior? Do I need to tell RedisGraph something is a float explicitly? If so, how can I do that? Didn't see this in the docs.

**Comment by jeffreylovitz** [comment]
Hi @LWprogramming,

Floating-point values are printed as strings, but internally are stored and operated on as standard 8-byte IEEE doubles.

This is because we print values using the Redis RESP 2 protocol, as described at https://oss.redislabs.com/redisgraph/result_structure/#scalars .

There's a RESP 3 protocol draft [in the works](https://gist.github.com/antirez/2bc68a9e9e45395e297d288453d5d54c) will introduce support for floating-point values as well as maps, sets, and other types. When that gets adopted, the display format should be a lot closer to the internal representation.

**Comment by LWprogramming** [comment]
Got it, thanks! 

How are integers stored, by the way?

**Comment by jeffreylovitz** [comment]
8-byte signed integers!
