### ISSUE TITLE
Build failure on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by andybenson** [RedisGraph/RedisGraph#621]
make fails on ubuntu with redis 5.05 and gcc 4.9.4 with errors

util.h:168:43: error: expected ';', ',' or ')' before 'buf'
 ssize_t snprintf_realloc(char ** restrict buf, size_t *bufcap, const char * restrict format, ...) __cypherlang_format(3, 4);

ast.c:392:5: error: expected declaration specifiers or '...' before '(' token
     (sizeof(struct cypher_astnode_vts) / sizeof(struct cypher_astnode_vt *)) <= UINT8_MAX,

**Comment by jeffreylovitz** [comment]
Hi @andybenson,

I'm attempting to reproduce this issue, but no luck yet!

These complaints are coming from compiling the dependency `libcypher-parser`. At least the first line relies on the C99 standard, but that should already be forced.

If you're able to test with a newer GCC version, that would be great! Otherwise, please provide the outputs of the following:
```
cd deps/libcypher-parser/
./autogen.sh
./configure
make clean check
```

This will generate _a lot_ of output, so you may want to redirect to file with directives like `make clean check >> build.log`

**Comment by andybenson** [comment]
Hi - Thanks - Ive upgraded gcc to 9 and its working now. So I will close
