### ISSUE TITLE
Different performance with different direction

### ISSUE THREAD

**Issue by dimaa6** [RedisGraph/RedisGraph#676]
I have loaded 44 million of Ethereum transactions into redisgraph. Now when I run:

GRAPH.QUERY ETHER_GRAPH "match (a: Address {address: '0xf265177f3bf84b55c68fd19eb884b224adce1881'})-[t: SENDS]->(b) return count(b)"
1) 1) "count(b)"
2) 1) 1) (integer) 4
3) 1) "Query internal execution time: 0.622734 milliseconds"

Let's switch direction:

localhost:8000> GRAPH.QUERY ETHER_GRAPH "match (a: Address {address: '0xf265177f3bf84b55c68fd19eb884b224adce1881'})<-[t: SENDS]-(b) return count(b)"
1) 1) "count(b)"
2) 1) 1) (integer) 4
3) 1) "Query internal execution time: 2378.543230 milliseconds"
(2.38s)

Why would it take so long for query which finds addresses which sent something to a, while looking for addresses to which a sent something is instant?

**Comment by jeffreylovitz** [comment]
Hi @dimaa6 ,

The direction specified in the query doesn't modify the traversals RedisGraph creates, so the pattern `MATCH (a)<-[]-(b)` is equivalent to the pattern `MATCH (b)-[]->(a)`.

The difference between your two queries is that in the first, the source node has an `address` filter, while in the second the filter is on the destination node. The module has a few heuristics for choosing how to construct traversals, and one is that it favors starting traversals from filtered nodes. If the destination is filtered, that means we need to transpose the adjacency matrix `t` so that we can traverse from destination to source.

I suspect that transposition is the bottleneck in the second query, but am uncertain of whether there are any flaws in the logic here. Traversing from `b` would require a scan of all `Address` nodes, which would be pretty wasteful!

One area we're testing for performance improvements is storing transposed adjacency matrices rather than computing them per-query, but currently only the overall adjacency matrix has this variant on `master`. If all of your edges between `Address` nodes are of the type `SENDS`, you could test this with the query:
`match (a: Address {address: '0xf265177f3bf84b55c68fd19eb884b224adce1881'})<-[t]-(b) return count(b)`

I hope this helps!

**Comment by dimaa6** [comment]
Hi @jeffreylovitz ,

Yes, edges are only of type SENDS, and leaving just [t] gives the same performance. Other products which implement Cypher (for example neo4j) can traverse without enforcing direction:

**Comment by jeffreylovitz** [comment]
It's important to keep in mind that Cypher doesn't prescribe the data model, and in fact the data model used by RedisGraph is quite different from that of Neo4j!

For Neo4j, each node maintains references to its incoming and outgoing edges (adjacency lists / index-free adjacency), so traversal direction is trivial.

Conversely, RedisGraph uses sparse matrices to store its edges, and in order to traverse from destination to source the matrix must first be transposed, which can be a bit time-consuming. This is most evident in cases like yours, where the query is only interested in a single source - the cost ameliorates pretty quickly as the number of pertinent source nodes increases.

This is an area that would be nice to optimize, but there are a lot of tradeoffs to consider, so we haven't formalized a design yet!

**Comment by dimaa6** [comment]
@jeffreylovitz I have tried to build redisgraph from the latest sources using [these instructions](https://oss.redislabs.com/redisgraph/#building) and succeeded, but got .so a little bit bigger than 100MB (I'm using Ubuntu 18.04):

110779280 redisgraph.so

In Docket image provided by redisgraph, size of that library is about 15MB:

-rwxr-xr-x 1 root root 15454280 Sep  5 09:05 /usr/lib/redis/modules/redisgraph.so

It would be OK if not for the crash of redis with library built by me when building an index:

GRAPH.QUERY ETHER_GRAPH "CREATE INDEX on :Address (address)"

This command brings redis down with SIGV. There is enough free RAM for this operation. Redis in docker builds this index even on bigger amount of data just fine.

Am I doing anything wrong? Is there a way to build redisgraph.so in the same way you do it?

**Comment by jeffreylovitz** [comment]
@dimaa6 The .so file created for the Docker image takes one extra step past the instructions you followed, which is to `strip` all symbol names. This drastically reduces the file size, but makes debugging a bit more difficult! If you'd like, you can do this as well:
```
$ du -sh src/redisgraph.so
120M    src/redisgraph.so
$ strip src/redisgraph.so
$ du -sh src/redisgraph.so
9.8M    src/redisgraph.so
```
(Your exact sizes might vary; I just ran this locally and have some modified code.)

Hopefully the bug and workaround I mentioned in #685 will solve your SEGV problem. If it doesn't, we'll dig deeper!

**Comment by jeffreylovitz** [comment]
Some sidenotes:
1) I always recommend working on master (Docker tag `edge`) or the most recent version available (currently, Docker tag `1.99.3).

2) We've started working on an optional optimization which would store the transposed versions of all adjacency matrices, reducing query time for your use case at the cost of greater RAM overhead.

**Comment by dimaa6** [comment]
@jeffreylovitz Thank you for your help, it is very valuable. I have tried image tagged `edge`, but still reverse lookup is slow:

**Comment by dimaa6** [comment]
@jeffreylovitz are you saying that this feature is still under development, but once developed, it will take about the same amount of memory it takes now when explicitly creating in and out edges?

**Comment by jeffreylovitz** [comment]
Yes, this will be approximately the same memory overhead as your current double-matrix approach! Development is ongoing at #684

**Comment by jeffreylovitz** [comment]
Traversal direction no longer has any performance difference, as we maintain transposed matrices by default.
